### ISSUE TITLE
Warning messages when using SOXAppDelegate

### ISSUE THREAD

**Issue by hokster7** [floriankrueger/SOXAppDelegate#2]
Thanks for this project. The ability to modularize `UIAppDelegate` was sorely needed and this project addresses that need well. =]

I followed the five-steps instructions on the README, and it looks like iOS isn't particularly happy about implementations of at least a couple of the methods:

``` objc
You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
2015-04-05 00:17:32.997 RecipeReview[38466:560624] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
2015-04-05 00:17:32.999 RecipeReview[38466:560624] Warning: Unable to create restoration in progress marker file
```

I could ignore these messages for now but definitely would be good to find a fix.

**Comment by floriankrueger** [comment]
Yes, this is a known issue. The thing is, `SOXAppDelegate` implements all the methods in the `UIApplicationDelegate` protocol to forward these (if you implement them) to your Services. 

`- application:performFetchWithCompletionHandler:` however is one of the background data processing methods and does not make sense if you're not enabling background processing for your app. That's all the first warning says. 

The second warning is caused by the methods `- application:shouldSaveApplicationState:` and `- application:shouldRestoreApplicationState:` which return `YES` in `SOXAppDelegate` if you don't override them. 

If you want to get rid of the warning, you would need to add `SOXAppDelegate` and `SOXService` to you project manually and remove those methods from `SOXAppDelegate`. Another approach would be to create four separate classes of `SOXAppDelegate`:
1. The standard, fully implemented version we have now
2. One without background methods but with state restoration methods
3. One without state restoration methods but with background methods
4. One without both state restoration and background methods

I would be happy to accept a pull request if you're willing to contribute. Otherwise I'll be looking into the issue again when there's more time. I hope this is fine for you ;)

**Comment by hokster7** [comment]
Hmm. @floriankrueger Thanks for your response. I imagined that was the case.  As soon as you provide a subclass implementation it barfs. That's fine.

Though on a broader note I was thinking that there must be a better way — with Objective-C being so dynamic and all that, surely `forwardInvocation:` could be a more generic and better approach to multiplexing calls to multiple `AppDelegates`.

A quick search reveals UrbanAirship has done something similar but not quite.
https://github.com/urbanairship/ios-library/blob/master/Airship/Common/UAAppDelegateProxy.m

https://github.com/aleph7/MultiDelegate uses `forwardInvocation` to great effect but it's designed to take an array of delegates through the initializer — a luxury that AppDelegate does not have.

I probably will use SOXAppDelegate as it is for now and keep you posted in the unlikely event that I do build an alternative implementation =]
